import Head from "next/head";
import { Intro, Whole, Sidebar } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jeremicah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/wave.png" />
      </Head>
      <main>
        {/* <Intro /> */}
        <Whole />
      </main>
    </>
  );
}
